### ISSUE TITLE
Error with dates

### ISSUE THREAD

**Issue by guycall** [activescaffold/active_scaffold_batch#5]
My application is Rails 4.1 / Ruby 2.1 / ActiveScaffold 3.4.30. In locales/en.yml I've defined the default date format as "%d-%b-%Y".

On the batch create form if a user enters a date formatted as 'dd/mm/yyyy' (e.g. 20/12/2016) rather than using the date picker, they get an error on this line:

https://github.com/activescaffold/active_scaffold/blob/master/lib/active_scaffold/attribute_params.rb#L169

```
 *** NoMethodError Exception: undefined method `errors' for nil:NilClass
```

The reason is that parent_record is nil. So not possible to add errors to it.

As an aside, looking at this line https://github.com/activescaffold/active_scaffold/blob/master/lib/active_scaffold/finder.rb#L151
_value_ at that point is still the string "01/12/2016" and I18n.t("date.formats.#{column.options[:format] || :default}") gives the format from my locales file "%d-%b-%Y"

This therefore sees _value_ as an invalid date. Whereas just using Date._parse(value) correctly parses the date. It might worth noting that even though my default format is set to "%d-%b-%Y", in Rails console the date gets processed correctly:

```
irb(main):008:0> t.anniversary = '02/12/2016'
=> "02/12/2016"
irb(main):009:0> t.save
   (0.5ms)  BEGIN
  SQL (0.6ms)  UPDATE `trainings` SET `anniversary` = '2016-12-02' WHERE `trainings`.`id` = 274426
   (1.0ms)  COMMIT
=> true
```

**Comment by scambra** [comment]
We use column.options[:format] || :default instead of Date._parse because Date._parse can give wrong dates, sometimes cannot guess if date format is american or european (or whatever you called), I mean Sep 10 is 09/10/year in american, but other formats use 10/09/year, which is Oct 9 in american format. It's not possible to guess what 10/09/year is without some hint from developer.

If you want to allow users write like dd/mm/yyyy, then set options[:format] for that column to a date format which is translated to dd/mm/yyyy
